# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tree.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 585)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gb_tree = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_tree.setGeometry(QtCore.QRect(130, 110, 361, 321))
        self.gb_tree.setObjectName("gb_tree")
        self.gridLayout = QtWidgets.QGridLayout(self.gb_tree)
        self.gridLayout.setObjectName("gridLayout")
        self.b1 = QtWidgets.QPushButton(self.gb_tree)
        self.b1.setObjectName("b1")
        self.gridLayout.addWidget(self.b1, 0, 4, 1, 1)
        self.b2 = QtWidgets.QPushButton(self.gb_tree)
        self.b2.setObjectName("b2")
        self.gridLayout.addWidget(self.b2, 1, 3, 1, 1)
        self.b3 = QtWidgets.QPushButton(self.gb_tree)
        self.b3.setObjectName("b3")
        self.gridLayout.addWidget(self.b3, 1, 5, 1, 1)
        self.b4 = QtWidgets.QPushButton(self.gb_tree)
        self.b4.setObjectName("b4")
        self.gridLayout.addWidget(self.b4, 2, 2, 1, 1)
        self.b5 = QtWidgets.QPushButton(self.gb_tree)
        self.b5.setObjectName("b5")
        self.gridLayout.addWidget(self.b5, 2, 4, 1, 1)
        self.b6 = QtWidgets.QPushButton(self.gb_tree)
        self.b6.setObjectName("b6")
        self.gridLayout.addWidget(self.b6, 2, 6, 1, 1)
        self.b7 = QtWidgets.QPushButton(self.gb_tree)
        self.b7.setObjectName("b7")
        self.gridLayout.addWidget(self.b7, 3, 1, 1, 1)
        self.b8 = QtWidgets.QPushButton(self.gb_tree)
        self.b8.setObjectName("b8")
        self.gridLayout.addWidget(self.b8, 3, 3, 1, 1)
        self.b9 = QtWidgets.QPushButton(self.gb_tree)
        self.b9.setObjectName("b9")
        self.gridLayout.addWidget(self.b9, 3, 5, 1, 1)
        self.b10 = QtWidgets.QPushButton(self.gb_tree)
        self.b10.setObjectName("b10")
        self.gridLayout.addWidget(self.b10, 3, 7, 1, 1)
        self.b11 = QtWidgets.QPushButton(self.gb_tree)
        self.b11.setObjectName("b11")
        self.gridLayout.addWidget(self.b11, 4, 0, 1, 1)
        self.b12 = QtWidgets.QPushButton(self.gb_tree)
        self.b12.setObjectName("b12")
        self.gridLayout.addWidget(self.b12, 4, 2, 1, 1)
        self.b13 = QtWidgets.QPushButton(self.gb_tree)
        self.b13.setObjectName("b13")
        self.gridLayout.addWidget(self.b13, 4, 4, 1, 1)
        self.b14 = QtWidgets.QPushButton(self.gb_tree)
        self.b14.setObjectName("b14")
        self.gridLayout.addWidget(self.b14, 4, 6, 1, 1)
        self.b15 = QtWidgets.QPushButton(self.gb_tree)
        self.b15.setObjectName("b15")
        self.gridLayout.addWidget(self.b15, 4, 8, 1, 1)
        self.gb_select = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_select.setGeometry(QtCore.QRect(270, 30, 431, 61))
        self.gb_select.setObjectName("gb_select")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gb_select)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.recordPaths = QtWidgets.QComboBox(self.gb_select)
        self.recordPaths.setEditable(False)
        self.recordPaths.setInsertPolicy(QtWidgets.QComboBox.InsertBeforeCurrent)
        self.recordPaths.setObjectName("recordPaths")
        self.recordPaths.addItem("")
        self.horizontalLayout.addWidget(self.recordPaths)
        self.toolButton = QtWidgets.QToolButton(self.gb_select)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.pushButton = QtWidgets.QPushButton(self.gb_select)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pb_plan = QtWidgets.QPushButton(self.centralwidget)
        self.pb_plan.setGeometry(QtCore.QRect(600, 210, 75, 61))
        self.pb_plan.setObjectName("pb_plan")
        self.pb_restart = QtWidgets.QPushButton(self.centralwidget)
        self.pb_restart.setGeometry(QtCore.QRect(600, 310, 75, 61))
        self.pb_restart.setObjectName("pb_restart")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gb_tree.setTitle(_translate("MainWindow", "数塔"))
        self.b1.setText(_translate("MainWindow", "9"))
        self.b2.setText(_translate("MainWindow", "12"))
        self.b3.setText(_translate("MainWindow", "15"))
        self.b4.setText(_translate("MainWindow", "10"))
        self.b5.setText(_translate("MainWindow", "6"))
        self.b6.setText(_translate("MainWindow", "8"))
        self.b7.setText(_translate("MainWindow", "2"))
        self.b8.setText(_translate("MainWindow", "18"))
        self.b9.setText(_translate("MainWindow", "9"))
        self.b10.setText(_translate("MainWindow", "5"))
        self.b11.setText(_translate("MainWindow", "19"))
        self.b12.setText(_translate("MainWindow", "7"))
        self.b13.setText(_translate("MainWindow", "10"))
        self.b14.setText(_translate("MainWindow", "4"))
        self.b15.setText(_translate("MainWindow", "16"))
        self.gb_select.setTitle(_translate("MainWindow", "GroupBox"))
        self.recordPaths.setCurrentText(_translate("MainWindow", "H:/py/python-machineLearn/source.txt/tree/one.txt"))
        self.recordPaths.setItemText(0, _translate("MainWindow", "H:/py/python-machineLearn/source.txt/tree/one.txt"))
        self.toolButton.setText(_translate("MainWindow", "浏览"))
        self.pushButton.setText(_translate("MainWindow", "确认"))
        self.pb_plan.setText(_translate("MainWindow", "动态规划"))
        self.pb_restart.setText(_translate("MainWindow", "重置"))

